CREATE TABLE Users (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(15) NOT NULL,
    Email NVARCHAR(100) NULL,
    Address NVARCHAR(300) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);